services:
  faq-bot:
    build: .
    image: faq-bot:latest
    container_name: faq-bot
    env_file:
      - .env
    environment:
      - DB_PATH=${DB_PATH:-/app/data/faq.db}
      - BOT_TOKEN=${BOT_TOKEN}
      - ADMIN_IDS=${ADMIN_IDS}
      - MENTION_THRESHOLD=${MENTION_THRESHOLD:-70}
      - NORMAL_THRESHOLD=${NORMAL_THRESHOLD:-80}
      - QA_CACHE_TTL=${QA_CACHE_TTL:-30}
      - QA_CACHE_AUTO_REFRESH=${QA_CACHE_AUTO_REFRESH:-false}
      - QA_CACHE_AUTO_INTERVAL=${QA_CACHE_AUTO_INTERVAL:-120}
      - APOLOGY_MSG=${APOLOGY_MSG}
      - NLP_MODEL_NAME=${NLP_MODEL_NAME:-paraphrase-multilingual-MiniLM-L12-v2}
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
    volumes:
      - ./data:/app/data
      - ./models:/app/models
      - ./hf_cache:/root/.cache/huggingface
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pgrep -f src/bot.py >/dev/null || exit 1"]
      interval: 60s
      timeout: 10s
      retries: 3

  init:
    image: faq-bot:latest
    command: ["python", "src/cli.py", "--db", "/app/data/faq.db", "--init"]
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    restart: "no"

  migrate:
    image: faq-bot:latest
    command: ["python", "src/cli.py", "--db", "/app/data/faq.db", "--migrate", "/app/data/qa.json", "/app/data/paraphrases.json"]
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    restart: "no"

  nlp:
    image: faq-bot:latest
    command: ["python", "src/cli.py", "--nlp"]
    env_file:
      - .env
    volumes:
      - ./models:/app/models
      - ./hf_cache:/root/.cache/huggingface
    restart: "no"
