version: "3.8"
services:
  faq-bot:
    build: .
    container_name: faq-bot
    env_file:
      - .env
    environment:
      - DB_PATH=${DB_PATH:-/app/data/faq.db}
      - BOT_TOKEN=${BOT_TOKEN}
      - ADMIN_IDS=${ADMIN_IDS}
      - MENTION_THRESHOLD=${MENTION_THRESHOLD:-70}
      - NORMAL_THRESHOLD=${NORMAL_THRESHOLD:-80}
      - QA_CACHE_TTL=${QA_CACHE_TTL:-30}
      - QA_CACHE_AUTO_REFRESH=${QA_CACHE_AUTO_REFRESH:-false}
      - QA_CACHE_AUTO_INTERVAL=${QA_CACHE_AUTO_INTERVAL:-120}
      - APOLOGY_MSG=${APOLOGY_MSG}
    volumes:
      - ./data:/app/data
      - ./models:/app/models
      - ./hf_cache:/root/.cache/huggingface
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "pgrep", "-f", "src/bot.py"]
      interval: 60s
      timeout: 5s
      retries: 3

  migrate:
    build: .
    image: faq-bot-migrate:latest
    command: ["python", "src/cli.py", "--db", "/app/data/faq.db", "--migrate", "/app/data/qa.json"]
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    restart: "no"

  nlp:
    build: .
    image: faq-bot-nlp:latest
    command: ["python", "src/cli.py", "--nlp"]
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ./models:/app/models
      - ./hf_cache:/root/.cache/huggingface
    restart: "no"
